# Generated by Django 4.0.5 on 2022-06-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_remove_mechanic2_salary_mechanic2_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='mechanic2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.mechanic2'),
        ),
    ]
